#!/usr/bin/env bash

osascript &>/dev/null <<EOF
    tell application "Terminal" to activate
    tell application "System Events" to tell process "Terminal" to keystroke "t" using command down
    tell application "System Events" to tell process "Terminal" to keystroke "cd $PWD"
    tell application "System Events" to tell process "Terminal" to key code 52
    tell application "System Events" to tell process "Terminal" to keystroke "PATH=$PATH:$PWD/node_modules/.bin/"
    tell application "System Events" to tell process "Terminal" to key code 52
    tell application "System Events" to tell process "Terminal" to keystroke "$*"
    tell application "System Events" to tell process "Terminal" to key code 52
EOF
